language: node_js

node_js:
  - "10"

cache: npm


stages:
  - test
  - release

jobs:
  include:
    - stage: test
      script:
        - npm i
        - npm run bootstrap
        - npm run test
    - stage: release
      if: branch = master
      deploy:
        provider: npm
        email: "zwhvv13@gmail.com"
        api_key: $NPM_API_KEY
        on:
          tags: true
        script:
          - npm i
          - npm run bootstrap
          - npm run publish
